### ISSUE TITLE
Feature Request: User Account Deletion and Information Update Functionality

### ISSUE THREAD

**Issue by PACY2** [PACY2/eco#35]
As a user of the system, I would like to have the ability to delete my account and update my information whenever necessary. This would provide me with greater control over my personal data and enable me to manage my account more effectively.

Specifically, I would like to see the implementation of two functionalities:

1. Account Deletion: Users should be able to delete their accounts, including any associated data, through a simple and secure process. This feature is important to ensure that users have full control over their data and can delete their accounts if they so desire.

1. Information Update: Users should be able to update their personal information (e.g., email address, name, password) through a user-friendly interface. This feature is important to ensure that users can easily keep their information up-to-date and accurate.

Overall, the implementation of these two features would greatly enhance the user experience and provide users with greater control over their personal data.

**Comment by ChoaibMouhrach** [comment]
- server side
- [x] Information Update
- [x] Information Update ( Tests / Fixes / Documentation ) 
- [x] Account Deletion
- [x] Account Deletion ( Tests / Fixes / Documentation ) 
- client side
- [x] Information Update
- [x] Account Deletion
