### ISSUE TITLE
Category Controller

### ISSUE THREAD

**Issue by PACY2** [PACY2/eco#7]
- [x] index
  - [x] Search
    - [x] id
    - [x] by name
  - [x] Sort
    - [x] id
    - [x] name
  - [x] Order
    - [x] desc 
    - [x] inc
  - [x] Fields
    - [x] id
    - [x] image
    - [x] name

- [x] store
  - [x] image
  - [x] name

- [x] update
  - [x] image
  - [x] name

- [x] destroy

- [x] Testing
  - [x] index
    - [x] sort
    - [x] fields
  - [x] store
  - [x] update
  - [x] delete

**Comment by ID-JA** [comment]
@PACY2 

https://github.com/PACY2/eco/blob/d1edc0fa66598bec406970e99c381db1a3415462/server/controllers/categoryController.ts#L119
when an item is deleted from the database, it is permanently removed, which can be problematic if we need to recover it later. By implementing a **soft delete** feature, we can change the status of the deleted item to indicate that it has been deleted, but still keep the item in the database. This way, we can recover it if needed.

There are different ways to implement **soft delete** but one common approach is to add a `deletedAt` field to the database table. When an item is deleted, we would update the `deletedAt` field with the current timestamp, but the item would still exist in the database. Then, when querying the database, we would exclude items that have a non-null `deletedAt` value.

```diff
const categorySchema = new Schema({
  name: {
    type: String,
    required: true,
    unique: true,
    dropDups: true
  },
  image: String
+ deletedAt: { type: Date, default: null }
})

```
